Repository michaelcaxias/trybe-schedule, pull requests merged in 2022-01, with the labels that each got.

#12 [CORREÇÃO] ajusta regex da captura de horario
  src/services/index.js
Labels: sugestão, pronto-para-o-merge

#11 [CORREÇÃO] - Ajusta mensagem de criação de evento
  package-lock.json
  src/components/AddEventButton.jsx
Labels: pronto-para-o-merge

#13 [CORREÇÃO] - Atualiza erro de português no placeholder
  src/components/TextArea.jsx
Labels: bug, pronto-para-o-merge

#28 [Avatar] - Layout 2.0
  src/components/LoginButton.jsx
  src/context/Provider.jsx
  src/images/blank-picture.png
  src/pages/Home.jsx
  src/styles/Home.scss
Labels: funcionalidade, layout-2.0

#24 [Layout 2.0] - Nova interface
  package-lock.json
  package.json
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/site.webmanifest
  src/components/AddEventButton.jsx
  src/components/Loading.jsx
  src/components/LoginButton.jsx
  src/components/SelectColors.jsx
  src/components/SelectTime.jsx
  src/components/TextArea.jsx
  src/context/Provider.jsx
  src/images/blank-picture.png
  src/images/logo.svg
  src/images/rocket.svg
  src/images/wavy.svg
  src/index.js
  src/pages/Home.jsx
  src/styles/AddEventButton.scss
  src/styles/Home.scss
  src/styles/Loading.scss
  src/styles/LoginButton.scss
  src/styles/SelectColors.scss
  src/styles/SelectTime.scss
  src/styles/TextArea.scss
  src/styles/home.css
  src/styles/index.scss
  src/styles/selectTime.css
Labels: layout-2.0
